### ISSUE TITLE
Masking

### ISSUE THREAD

**Issue by znicholls** [SantanderMetGroup/ATLAS#10]
Another question (sorry for having so many @miturbide!). I wanted to check that I have correctly understood how your masking works. 

https://github.com/SantanderMetGroup/ATLAS/blob/8824f76f35fbdf6b6aea76fdf6fc1fcbd9f5568f/aggregated-datasets/scripts/calculate_regional_means.R#L33 suggests that any region with a surface land fraction greater than 0.999 is classified as land. https://github.com/SantanderMetGroup/ATLAS/blob/8824f76f35fbdf6b6aea76fdf6fc1fcbd9f5568f/aggregated-datasets/scripts/calculate_regional_means.R#L34 suggests that any region with a surface land fraction less than 0.001 is classified as sea.

Does this mean that any cell with surface land fraction greater than 0.001 and less than 0.999 (about 5% of cells looking at https://github.com/SantanderMetGroup/ATLAS/blob/master/reference-grids/land_sea_mask_1degree.nc4) is not included in either the sea or land calculation? In other words, only cells which are clearly one or the other are included in the masked averages?

**Comment by gutierjm** [comment]
Yes. We compute land and ocean results from purely land or ocean griboxes and discard the mixed (coastal) ones.

**Comment by znicholls** [comment]
thanks @gutierjm, do you have any thoughts on #11 ?
