### ISSUE TITLE
typo in variable info for Heating Degree Days

### ISSUE THREAD

**Issue by nelerey** [SantanderMetGroup/ATLAS#16]
In the information displayed when hovering over the (i) next to Heating Degree Days in the Variable tab, it talks about "CDD". However, reading [Spinoni et al. (2015)](https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/joc.3959), I believe this should be "HDD" or "HD" instead: _"We distinguish between cooling degree-days (CDD), heating degree-days (HDD), and growing degree-days (GDD)."_

(This atlas is awesome and I'm nitpicking, thanks for creating this fantastic resource!)

**Comment by jesusff** [comment]
Thank you for reporting. This has been fixed in a new version of the Interactive Atlas, to be released on Sep 27.
