### ISSUE TITLE
Regional mean weighting

### ISSUE THREAD

**Issue by znicholls** [SantanderMetGroup/ATLAS#8]
Hi there,

Thanks for all your efforts with the ATLAS. I have what I hope is a quick question: after you've interpolated the files onto a common grid, are your regional-means weighted by cell area, or are they simply a mean over all the cells (giving each cell equal weight)? This would be great to know for some analysis I'm doing.

Thanks!

**Comment by znicholls** [comment]
I did some more thinking and I don't think my original question is that helpful so will close this and open a new issue.

**Comment by miturbide** [comment]
Hi znicholls , thanks for your question. 
Regional averages are weighted by the cosine of the latitude. We have included this information in the README:
https://github.com/SantanderMetGroup/ATLAS/tree/master/aggregated-datasets
